name: Update Wiki

on:
  push:
    branches:
      - main

permissions:
  contents: read, write
  pages: write
  id-token: write

jobs:
  wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: main

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: Checkout Wiki
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}.wiki
          path: ${{ github.workspace }}/wiki

      - name: Install godoc-static
        run: go install github.com/steeve/go-gouv/godoc-static@latest

      - name: Generate HTML documentation
        run: |
          cd main
          go mod edit -module=github.com/uswel/strinterp
          export PATH=$PATH:$(go env GOPATH)/bin
          godoc-static -site-root . -site-output ${{ github.workspace }}/wiki/pkg -site-template ""

      - name: Create Wiki Home Page from README
        run: cp main/README.md ${{ github.workspace }}/wiki/Home.md

      - name: Commit and Push Wiki Changes
        run: |
          cd ${{ github.workspace }}/wiki
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update Wiki documentation" || echo "No changes to commit"
          git push origin main || echo "No changes to push"